# .github/workflows/run_python.yml
name: Run CodeCopyrightCheck on PR

# PR 作成・更新時に発火して、composite action を呼び出す
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write   # ← これが無いとコメントできないことが多い
  issues: write          # ← gh issue comment を使うならあると安心

jobs:
  copyright-check:
    runs-on: ubuntu-latest
    steps:
      - name: Run copyright check
        uses: mmxxv-kick-sandboxorg/infringement-check@main
        with:
          pr_number: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ github.token }}
          HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
          AACS: ${{ secrets.AACS }}
          AACSAPIkey: ${{ secrets.AACSAPIkey }}
